IF DB_ID('VotingDApp') IS NOT NULL
BEGIN
    ALTER DATABASE VotingDApp SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE VotingDApp;
END;
GO

CREATE DATABASE VotingDApp;
GO

USE VotingDApp;
GO

IF SCHEMA_ID('voting') IS NULL
BEGIN
    EXEC('CREATE SCHEMA voting');
END;
GO
